channels:
  - conda-forge
dependencies:
  - threadpoolctl
  - qp
  - cython
  - nbconvert
  - ipykernel
  - lsstdesc-gcr-catalogs
  - compilers
  - guppy3
  - mockmpi
  - pygraphviz
  - lsstdesc-dc2-dm-data
  - psycopg2
  # RAIL wants these additional ones
  - pyarrow
  - pytables
  - somoclu
