channels:
  - conda-forge
dependencies:
  - threadpoolctl
  - qp
  - compilers
  - nbconvert
  - ipykernel
  - lsstdesc-gcr-catalogs
  - guppy3
  - mockmpi
  - pygraphviz
  - lsstdesc-dc2-dm-data
  - psycopg2
