channels:
  - conda-forge
dependencies:
  - threadpoolctl
  - qp
  - cython=3.0.*
  - nbconvert
  # rail requires 3.12
  - python=3.11.*
  - ipykernel
  - lsstdesc-gcr-catalogs
  - compilers
  # - guppy3
  - mockmpi
  - pygraphviz
  - lsstdesc-dc2-dm-data
  - psycopg2
  # RAIL wants these additional ones
  - pyarrow
  - pytables
  - somoclu
