name: Build NERSC Version 

on: workflow_dispatch
                
jobs:
  build:
    name: Build Basic NERSC Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3


      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mpi4py-nersc-version
          file: ./mpi4py-nersc-version/Dockerfile
          push: true
          tags: ghcr.io/lsstdesc/mpi4py-nersc-version
          cache-from: type=gha
          cache-to: type=gha,mode=max
