name: Build Developer Image

on: workflow_dispatch



jobs:
  build:
    name: Build Developer Image
    uses: ./.github/workflows/build-an-image.yml
    with:
      IMAGE_NAME: ${{ github.repository }}
      BUILD_DIR: ./txpipe-dev
      TEST_TAG: lsstdesc/txpipe-dev:testing
      PUSH_TAG: ghcr.io/lsstdesc/txpipe-dev
