name: Build Docker Production Image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    name: Build Dev Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Get current date
        id: date
        run: 

      - name: Find Release Tag
        id: find_release_tag
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./txpipe-dev
          file: ./txpipe-dev/Dockerfile
          build-args: |
            TX_DOCKER_VERSION=${{ github.sha }}
            TX_RELEASE_TAG=${{ steps.find_release_tag.outputs.tag }}
          push: true
          tags: 
          tags:
            - ghcr.io/joezuntz/txpipe-docker:latest
            - ghcr.io/joezuntz/txpipe-docker:${{ steps.find_release_tag.outputs.tag }}
            - ghcr.iojoezuntz/txpipe-docker:${{ steps.find_release_tag.outputs.date }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
