name: Build Production Image

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Production Image
    uses: ./.github/workflows/build-an-image.yml
    with:
      IMAGE_NAME: ${{ github.repository }}
      BUILD_DIR: ./txpipe
      TEST_TAG: lsstdesc/txpipe:latest
      PUSH_TAG: ghcr.io/lsstdesc/txpipe
  