name: Create and publish a Docker image

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    name: Build Dev Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./txpipe-dev
          file: ./txpipe-dev/Dockerfile
          build-args: |
            TX_DOCKER_VERSION=${{ github.sha }}
            TX_RELEASE_TAG=dev
          push: true
          tags: joezuntz/txpipe-dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
